# Generated by Django 4.2.6 on 2023-10-17 07:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("snippets", "0002_alter_snippet_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="snippet",
            old_name="lanage",
            new_name="language",
        ),
    ]
